language: groovy
sudo: false
cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
jdk:
- oraclejdk8
install: true
script: "./travis-build.sh"
env:
  global:
  - secure: UP941pwl46g7H6X1uUTaXlDZR4c86BWLA+e6wQT13gfCkhFANoiwBi9UjF1+osbtREkLJrvMlwF+ZizBYw+vr9EFGWMu6xuziohvVHpKkdCvvfPZYRg8QtlRrcd4szWNuUdK4j448FxmPcaSjshHCgQhFaIHTV6hFTvocPSh10M=
  - secure: JoWtWyfRCmmoUe0tvHmnDWk0goFPSLmCF7HOB+aOrBU+12uGhY9mLgItJAEgwa29Mu5Ts4HHrqeht0MgK2xF1dOFzzbqskWa07J/YaC+S6RqdcDZ0Xd2XIlu49es3b8OzhLCPxjl7l9U9CeCt5s0W9NQviyA9lroFdiqirRioJA=
  - secure: P0hOLy6be2FbLQ4F967aH0LXfcULpL/m3umQOG6tibHMxycqRzsUsbY39gF4Y+VDCMzxPT2DFg3zM+i4Nt8npLcLmcn/T56cjWQ0p++5/q5DvbItyZFAdV3FDUtDohQl37aWewXJHOXuPe6VSwa8KkjksH7i7AO0W9OSZiIp2WM=
  - secure: gvLsQ+CPQSQE9jNmb+LhWXKRPho0hjhxJKZkyrm2wnPDW1pbwBLxJy0RVFPsxrWYyL/kZZSEY8QvIwibBYW8OAP6weA/DIGz4y5o0IaOpEJT82kSaGggE6LaNOkjDDATDkLEhZoORVqNz9tlj1w0Eg+VzA0RO+CAzrObjKA8E/Y=
  - secure: 0Bq+Jg2PRW37sQQaMVFUti2SfDurAYAYOosaDFfpnEhvEqnZJiibtB0EExM7wdH0ew63DES9xL2jC88yCK5BUaW/BP8hZtPF1pBCIr5+f06yHCr5PVVQmr6eCkBYYRzZM2dVAKvhs6eA+HbE7NhHnX5FhAqHULWloSfFlh3YPb0=
