grails:
   profile: web
   spring:
      transactionManagement: false
info:
   app:
      name: '@info.app.name@'
      version: '@info.app.version@'
      grailsVersion: '@info.app.grailsVersion@'
server:
   port: 8238
spring:
   groovy:
      template:
         check-template-location: false
